@startmindmap
* Безопасность данных

** Публичные данные
*** Данные о компании
**** Искажение данных - Незначительный
***** Порча данных о компании на сайте может вести к некоторым репутационным издержкам

** Внутренние данные
*** Данные о недвижимости
**** Искажение данных - Незначительный
***** Эти данные доступны для публичного просмотра на сайте, но внутренняя система управления ими требует защиты от несанкционированных изменений.
**** Обесценивание данных - Незначительный 
***** Данные могут утратить актуальность, что негативно скажется на клиентском опыте
**** Некачественные данные - Незначительный
***** Данные могут содержать ошибки, например фото и планировка не соответствуют друг другу
*** Системные и технические данные
**** Утечка данных - Значительный
***** Утечка системных данных облегчит кибератаки. 
**** Потеря данных - Незначительный
***** Потеря логов и данных о сетевой инфраструктуре приведет к снижению уровня сервиса в системе, что ведет в первую очередь к репутационным издержкам.
**** Искажение данных - Значительный
***** Несанкционированный доступ к логам может скрыть следы инцидентов безопасности.
**** Некачественные данные - Незначительный
***** Некорректные данные о сетевой инфраструктуре и логи снижают эффективность обслуживания информационной системы и следовательно - негативно влияют на пользовательский опыт.

** Конфиденциальные данные
*** Персональные данные клиентов и собственников
**** Утечка данных - Критический
***** Утечка этих данных может привести к серьёзным последствиям, включая мошенничество, а также нарушения законодательства о защите персональных данных.
**** Потеря данных - Значительный
***** Потеря данных может привести к репутационным рискам, операционным проблемам и финансовым потерям, возможны юридические последствия при нарушении условий договоров
**** Искажение данных - Значительный
***** Искажение данных вызовет финансовые, репутационные и возможно юридические последствия
*** Данные о сделках
**** Утечка данных - Критический
***** Если эти данные попадут в руки злоумышленников, это может привести к серьезным финансовым и репутационным потерям. Есть вероятность юридического разбирательства.
**** Потеря данных - Значительный
***** Утрата или искажение чувствительных данных может привести к операционным сбоям и нарушению обязательств по договорам.
**** Искажение данных - Значительный
***** Утрата или искажение чувствительных данных может привести к операционным сбоям и нарушению обязательств по договорам.

** Секретные данные
*** Финансовые данные
**** Утечка данных - Критический
***** Утечка финансовых данных может привести к значительным убыткам и нарушениям законодательства, связанным с защитой данных платёжных карт.
**** Потеря данных - Значительный
***** Потеря или искажение этой информации  может привести к операционным сбоям.
**** Искажение данных - Значительный
***** Потеря или искажение этой информации  может привести к операционным сбоям.
**** Некачественные данные - Незначительный
***** Если эти данны будут содержать некачественную, или недостоверную информацию, то это приведет к снижению эффективности аналитики.
*** Секреты
**** Утечка данных - Критический
***** Если эти данные окажутся в руках злоумышленников, то это значительно повысит шансы кибератак на успех
**** Потеря данных - Критический
***** Потеря и искажение этих данных опасны в равной степени и потенциально ведут к утрате самых ценных данных компании, а следовательно к юридическим и финансовым последствиям
**** Искажение данных - Критический
***** Потеря и искажение этих данных опасны в равной степени и потенциально ведут к утрате самых ценных данных компании, а следовательно к юридическим и финансовым последствиям
**** Обесценивание данных - Значительный
***** Устаревшие ключи и сертификаты снижают эффективность защитных мероприятий


@endmindmap